package ed.inf.grape.L;

import java.util.ArrayList;
import java.util.List;

import ed.inf.grape.core.Message;
import ed.inf.grape.core.Query;
import ed.inf.grape.core.Result;
import ed.inf.grape.graph.Partition;

public class LocalComputeTask {

	/** assign a partition to this task */
	private int partitionID;

	/** messages generated by this step */
	private List<Message> messages;

	/** results generated by this step */
	private List<Result> results;

	public LocalComputeTask(int partitionID) {
		this.partitionID = partitionID;
		this.messages = new ArrayList<Message>();
		this.results = new ArrayList<Result>();
	}

	public int getPartitionID() {
		return this.partitionID;
	}

	public List<Message> getMessages() {
		/**
		 * return the messages generated by this local compute.
		 */
		return (this.messages.size() == 0) ? null : this.messages;
	}

	public List<Result> getResults() {
		/**
		 * return the results generated by this local compute.
		 */
		return (this.results.size() == 0) ? null : this.results;
	}

	public void compute(Query query, Partition partition) {
		/**
		 * a method need to implemented by client
		 * 
		 * define compute, also fulfil messages and results.
		 * 
		 */
	}
}
